# Generated by Django 4.2.1 on 2023-06-05 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alumnos_asignaturas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="alumnos_asignaturas",
            table="alumnos_asignaturas",
        ),
    ]
