# Generated by Django 4.2.1 on 2023-06-19 04:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alumnos_asignaturas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alumnos_asignaturas",
            old_name="profesor",
            new_name="alumno",
        ),
    ]
