# Generated by Django 4.2.1 on 2023-06-05 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profesores_asignaturas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profesores_asignaturas",
            table="profesores_asignaturas",
        ),
    ]
