# Generated by Django 4.2.1 on 2023-06-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_cuenta", models.PositiveIntegerField()),
                ("academia", models.TextField()),
                ("nivel", models.TextField()),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "db_table": "Profesor",
            },
        ),
    ]
